spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: test
      port: 27017
      host: localhost
      auto-index-creation: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
